
from tkinter import *
root=  Tk()
root.title("Driving License")
root.geometry("400x400")
label_Drive=Label(root, text="Driving License")
label_id=Label(root, text="id: 5693400000957")
label_Name=Label(root, text="Name: Baibhav Dhamla")
label_DOB=Label(root, text="Date of Birth: 01-02-2011")
label_Pin=Label(root, text="Pin No: 734003")
label_Address=Label(root, text="Address: Milanmore, Siliguri, West Bengal")
label_vehicle_type=Label(root, text="Authorisation To Drive The Following Vehicles: Two Four")
label_Drive.pack()
label_id.pack()
label_Name.pack()
label_DOB.pack()
label_Pin.pack()
label_Address.pack()
label_vehicle_type.pack()
root.mainloop()
